[tool.black]
line-length = 120
terget-version = ["py311"]
extend-exclude = '''
venv
'''

[tool.autoflake]
check = true
in-place = true
remove-unused-variables = true
remove-dublicate-keys = true
remove-all-unused-imports = true